version: '3.8'

services:
  secureapp:
    image: dawills2024/secureapp:latest  # Tu imagen subida a Docker Hub
    container_name: secureapp-container
    ports:
      - "7000:5002"  # Mapea el puerto 7000 en tu máquina al puerto 5002 en el contenedor
    environment:
      - SECRET_KEY=supersecretkey
      - DATABASE_URL=sqlite:///instace/rbacSec.db  # Ruta de la base de datos dentro del contenedor
      - JWT_SECRET_KEY=supersecretjwtkey
    volumes:
      - ./src:/app/src  # Mapea el directorio local 'src' al directorio '/app/src' en el contenedor
      - ./src/instace:/app/src/instace # Mapea
    restart: always  # Asegura que el contenedor se reinicie si falla
